steps:
- id: 'repository'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - | 
        cd terraform/prebuild      
        terraform init
        terraform workspace select prebuild || terraform workspace new prebuild
        terraform init
        terraform apply -auto-approve
  env:
  - 'TF_VAR_repository=${_REPOSITORY}'
  - 'TF_VAR_region=${_REGION}'
- id: 'build'
  name: "gcr.io/cloud-builders/docker"
  args:
      [
        "build",
        "-t",
        "$_REGION-$_REPOSITORY_BASE_URL/$PROJECT_ID/$_REPOSITORY/helloworld:$SHORT_SHA",
        "-t",
        "$_REGION-$_REPOSITORY_BASE_URL/$PROJECT_ID/$_REPOSITORY/helloworld:latest",
        "-f",
        "cloudrun/helloworld/Dockerfile",
        "."
      ]
  env:
  - 'REGION=${_REGION}'
  - 'REPOSITORY_BASE_URL=${_REPOSITORY_BASE_URL}' 
  - 'REPOSITORY=${_REPOSITORY}'
- id: 'push' 
  name: "gcr.io/cloud-builders/docker"
  args: ["push", "$_REGION-$_REPOSITORY_BASE_URL/$PROJECT_ID/$_REPOSITORY/helloworld"]
  env:
  - 'REGION=${_REGION}'
  - 'REPOSITORY_BASE_URL=${_REPOSITORY_BASE_URL}' 
  - 'REPOSITORY=${_REPOSITORY}'
- id: 'tf'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        cd terraform/postbuild 
        terraform init
        terraform workspace select postbuild || terraform workspace new postbuild 
        terraform init
        terraform apply -auto-approve -replace="google_cloud_run_service.cloudrun-srv"
substitutions:  
  _REPOSITORY_BASE_URL: docker.pkg.dev
  _REPOSITORY: helloworld
  _REGION: us-central1
options:
  substitution_option: 'ALLOW_LOOSE'
