steps:
- id: 'registry'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - | 
        cd terraform/prebuild      
        terraform init
        #terraform plan
        terraform workspace select prebuild || terraform workspace new prebuild
        terraform apply -auto-approve
  env:
  - 'TF_VAR_registry=${_REGISTRY}'
  - 'TF_VAR_region=${_REGION}'
- id: 'build'
  name: "gcr.io/cloud-builders/docker"
  args:
      [
        "build",
        "-t",
        "$_REGION-$_REGISTRY_BASE_URL/$PROJECT_ID/$_REGISTRY/helloworld:$SHORT_SHA",
        "-t",
        "$_REGION-$_REGISTRY_BASE_URL/$PROJECT_ID/$_REGISTRY/helloworld:latest",
        "-f",
        "cloudrun/helloworld/Dockerfile",
        "."
      ]
  env:
  - 'REGION=${_REGION}'
  - 'REGISTRY_BASE_URL=${_REGISTRY_BASE_URL}' 
  - 'REGISTRY=${_REGISTRY}'
- id: 'push' 
  name: "gcr.io/cloud-builders/docker"
  args: ["push", "$_REGION-$_REGISTRY_BASE_URL/$PROJECT_ID/$_REGISTRY/helloworld"]
  env:
  - 'REGION=${_REGION}'
  - 'REGISTRY_BASE_URL=${_REGISTRY_BASE_URL}' 
  - 'REGISTRY=${_REGISTRY}'
- id: 'tf'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        cd terraform/postbuild 
        terraform init
        #terraform plan
        terraform workspace select postbuild || terraform workspace new postbuild 
        terraform apply -auto-approve -replace="google_cloud_run_service.cloudrun-srv"
substitutions:  
  _REGISTRY_BASE_URL: docker.pkg.dev
  _REGISTRY: cloud-services-repository
  _REGION: us-central1
options:
  substitution_option: 'ALLOW_LOOSE'
