steps:
- id: 'tf'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        cd terraform      
        terraform init
        terraform plan
        #terraform apply -auto-approve
